# Generated by Django 4.0.3 on 2022-03-31 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='Images/')),
                ('uploader', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=400)),
            ],
        ),
    ]
