# Generated by Django 4.0.3 on 2022-04-01 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_coment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Coment',
            new_name='Comment',
        ),
    ]
