# Generated by Django 4.0.3 on 2022-04-01 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_post_date_added'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='date_added',
        ),
    ]
