# Generated by Django 4.0.3 on 2022-04-01 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_remove_post_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.TextField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='uploader',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
