# Generated by Django 4.0.3 on 2022-03-08 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Full_Name', models.CharField(max_length=200)),
                ('Email', models.EmailField(max_length=200)),
                ('IsParent', models.CharField(choices=[('Parent', 'Parent'), ('Student', 'Student')], default='Parent', max_length=20)),
                ('Content', models.TextField(max_length=400)),
            ],
        ),
    ]
