# Generated by Django 4.0.3 on 2022-03-08 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='IsParent',
            field=models.CharField(choices=[('Parent', 'Parent'), ('étudiant', 'étudiant')], default='Parent', max_length=20),
        ),
    ]
